#replace "" with the values for each
host: ""
port: ""
database: ""
username: ""
password: ""
table: ""
#if you wish to change the lore or the item name you can do so here
item-name: "Item Frame"
item-lore: "This item frame allows for the copying of books"